# ADJUST THESE DATABASE SETTINGS AS NECESSARY.
database:
  ==: vg.civcraft.mc.civmodcore.dao.DatabaseCredentials
  host: localhost
  port: 3306
  db: minecraft
  poolSize: 1
  user: mc
  pass: mc
  connection_timeout: 10000
  idle_timeout: 600000
  max_lifetime: 7200000

# custom model ids for the respective items
custom_model_ids:
  fingerprint: -1
  fingerprint_book: -1

# The number of prints allowed to occupy one block
max_prints_per_block: 5
items:
  duster:
    material: WOODEN_SWORD
    name: Fingerprint Duster
    lore:
      - 'A feather duster used to find fingerprints'
      - '[!] Requires ink'
    uses: 10
  ink:
    material: WOODEN_SWORD
    name: Inkwell
    lore:
      - 'Ink applied to surfaces to find fingerprints'
      - '[!] Requires a duster'
    uses: 5
  magnifying_glass:
    material: STICK
    name: Magnifying Glass
    lore:
      - 'Memories of burning ants'
      - 'This could be used to see fingerprints'

# Integer denoting which effect you want a specific action to cause
  # 11 = CRIT_MAGIC,
  # 30 = REDSTONE,
  # 90 = ELECTRIC_SPARK,
effects:
  volunEffect: 90
  trespassEffect: 90
  rummageEffect: 90
  theftEffect: 90
  assaultEffect: 30
  murderEffect: 30
  vandaEffect: 90
  

# ALL CHANCES ARE 0-1 PERCENTAGE
reason_settings:
  #complete
  trespassing:
    bastion_types: [vault]
    chance: 0.05
  #complete
  rummaging:
    # Locked = reinforced, unlocked = not reinforced
    locked_chance: 0.07
    unlocked_chance: 0.02
  #complete
  theft:
    locked_chance: 0.07
    unlocked_chance: 0.02
  #complete
  assault:
    pvp_chance: 0.1
    pve_chance: 0.02
    player_allowed_on_bastion_multiplier: 0.8
    ignore_bastion_for_pvp: true
  #complete
  murder:
    pvp_chance: 1
    pve_chance: 0.1
    player_allowed_on_bastion_multiplier: 0.8
    ignore_bastion_for_pvp: true
  #complete
  vandalism:
    bastion_break_chance: 0.33
    block_break_chance: 0.05
    ignore_break_if_on_bastion: true
